version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - algorithms-{{ checksum "pom.xml" }}
            - algorithms-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
          - ~/.m2
          key: algorithms-{{ checksum "pom.xml" }}
      - run: mvn test -B
#            - run: mvn test -B# - run: mvn integration-test


workflows:
  version: 2
  algorithms:
    jobs:
      - build
